// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYDfPJC9390QNJ3mD0CRkoPOKcsANK4fU',
    appId: '1:226045461060:web:75453061f8e8ff5641f211',
    messagingSenderId: '226045461060',
    projectId: 'my-notewise-app',
    authDomain: 'my-notewise-app.firebaseapp.com',
    storageBucket: 'my-notewise-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuA6L1zAM76AT36wQdAAKdB8HHAn9VuTk',
    appId: '1:226045461060:android:ada7b9b06710c36d41f211',
    messagingSenderId: '226045461060',
    projectId: 'my-notewise-app',
    storageBucket: 'my-notewise-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ANHmkMoTdv1uswP7e6dEe3yRZWslj8s',
    appId: '1:226045461060:ios:2609b66ac8649f7941f211',
    messagingSenderId: '226045461060',
    projectId: 'my-notewise-app',
    storageBucket: 'my-notewise-app.appspot.com',
    iosClientId: '226045461060-4i8sle8pnn6lo0joobn1o12r1b51dvh3.apps.googleusercontent.com',
    iosBundleId: 'com.notr.rightcrowdmedia.notewise',
  );
}
